import { Audio } from "@remotion/media";
import type React from "react";
import { interpolate, staticFile, useVideoConfig } from "remotion";
import { AD_DURATION } from "./brand";

// The ad's soundtrack: a 20-second, 120 BPM music bed arranged to the scenes
// (hook 0-90, pain 90-225, proof 225-390, offer 390-495, CTA 495-600) plus
// one-shot effects on the visual events they accompany. Frames are absolute
// ad frames at 30 fps; one beat = 15 frames. Generated by
// scripts/generate-ad-audio.mjs (music mastered to about -13.5 LUFS).
export const AdSound: React.FC = () => {
  const { fps } = useVideoConfig();

  return (
    <>
      <Audio
        name="Music"
        src={staticFile("audio/ad-music.wav")}
        volume={(f) =>
          interpolate(f, [AD_DURATION - 10, AD_DURATION], [0.85, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          })
        }
        premountFor={fps}
      />

      {/* Hook */}
      <Audio
        name="Tick: hook line 1"
        src={staticFile("audio/ad-tick.wav")}
        from={15}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Tick: hook line 2"
        src={staticFile("audio/ad-tick.wav")}
        from={30}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Tick: hook line 3"
        src={staticFile("audio/ad-tick.wav")}
        from={45}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Impact: hook payoff"
        src={staticFile("audio/ad-impact.wav")}
        from={60}
        volume={0.5}
        premountFor={fps}
      />

      {/* Pain */}
      <Audio
        name="Stamp: pain 1"
        src={staticFile("audio/ad-stamp.wav")}
        from={100}
        volume={0.7}
        premountFor={fps}
      />
      <Audio
        name="Stamp: pain 2"
        src={staticFile("audio/ad-stamp.wav")}
        from={130}
        volume={0.7}
        premountFor={fps}
      />
      <Audio
        name="Stamp: pain 3"
        src={staticFile("audio/ad-stamp.wav")}
        from={160}
        volume={0.7}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: acid panel"
        src={staticFile("audio/ad-whoosh.wav")}
        from={180}
        volume={0.45}
        premountFor={fps}
      />

      {/* Proof */}
      <Audio
        name="Tick: proof title 1"
        src={staticFile("audio/ad-tick.wav")}
        from={225}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Tick: proof title 2"
        src={staticFile("audio/ad-tick.wav")}
        from={240}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: project 1"
        src={staticFile("audio/ad-whoosh.wav")}
        from={255}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: project 2"
        src={staticFile("audio/ad-whoosh.wav")}
        from={300}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: project 3"
        src={staticFile("audio/ad-whoosh.wav")}
        from={345}
        volume={0.4}
        premountFor={fps}
      />

      {/* Offer */}
      <Audio
        name="Tick: promise 2"
        src={staticFile("audio/ad-tick.wav")}
        from={405}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Tick: promise 3"
        src={staticFile("audio/ad-tick.wav")}
        from={420}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Stamp: price"
        src={staticFile("audio/ad-stamp.wav")}
        from={450}
        volume={0.7}
        premountFor={fps}
      />
      <Audio
        name="Impact: price"
        src={staticFile("audio/ad-impact.wav")}
        from={450}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Riser: into CTA"
        src={staticFile("audio/ad-riser.wav")}
        from={450}
        volume={0.4}
        premountFor={fps}
      />

      {/* Call to action */}
      <Audio
        name="Impact: CTA"
        src={staticFile("audio/ad-impact.wav")}
        from={495}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Tick: domain"
        src={staticFile("audio/ad-tick.wav")}
        from={510}
        volume={0.38}
        premountFor={fps}
      />
      <Audio
        name="Click: start a project"
        src={staticFile("audio/ad-click.wav")}
        from={540}
        volume={0.6}
        premountFor={fps}
      />
    </>
  );
};
