import { Audio } from "@remotion/media";
import type React from "react";
import { staticFile, useVideoConfig } from "remotion";

// The soundtrack of "Nothing Happened.": a 20-second, 120 BPM music bed plus
// one-shot effects on the visual events they accompany. Frames are absolute
// ad frames at 30 fps (one beat = 15 frames, one bar = 60), so mount this at
// the top of the composition. Generated by scripts/generate-ad3-audio.mjs: the
// bed is mastered to about -14 LUFS (true peak about -2 dBTP) and fades out on
// its own over 570-600; every effect is peaked at -5 dBTP with its momentary
// loudness capped at -14 LUFS (subs -12), so a level below means about the
// same prominence for a click as for a bell. With these levels the whole mix
// peaks around -1 dBFS.

type Cue = {
  name: string;
  file: string;
  from: number;
  // Level in dB (0 = the file as rendered).
  db: number;
};

const cue = (name: string, file: string, from: number, db: number): Cue => ({
  name,
  file,
  from,
  db,
});

const dbToGain = (db: number) => 10 ** (db / 20);

// Alternating two key sounds so typing does not machine-gun.
const typing = (label: string, frames: number[], db: number): Cue[] =>
  frames.map((from, i) =>
    cue(
      `Tick: ${label} ${i + 1}`,
      i % 2 ? "ad3-tick-down2" : "ad3-tick",
      from,
      db,
    ),
  );

const CUES: Cue[] = [
  // Hook (0-75): the tap that does nothing.
  cue("Tap: open", "ad3-tap", 0, -4),
  ...Array.from({ length: 11 }, (_, i) =>
    cue(`Tick: spinner ${i + 1}`, "ad3-tick", 8 + i * 5, -18),
  ),
  cue("Thud", "ad3-thud", 30, -10),
  cue("Tap: retry 1", "ad3-tap", 44, -8),
  cue("Bonk: dead button", "ad3-bonk", 45, -4),
  cue("Tap: retry 2", "ad3-tap", 48, -8),
  cue("Swipe", "ad3-swipe", 59, -6),
  cue("Sink", "ad3-sink", 66, -12),

  // The cost (75-150).
  cue("Sub: the cost", "ad3-sub", 75, -6),

  // The drop (150).
  cue("Tap: drop", "ad3-tap", 150, 0),
  cue("Swoosh: drop", "ad3-swoosh", 150, -6),
  cue("Chime: first win", "ad3-chime", 166, -6),
  cue("Tick: roll", "ad3-tick", 183, -10),
  cue("Buzz 1", "ad3-buzz", 186, -8),
  cue("Buzz 2", "ad3-buzz", 198, -8),
  cue("Tap: answer", "ad3-tap", 204, -4),
  cue("Pop: blip low", "ad3-pop", 206, -6),
  cue("Pop: blip high", "ad3-pop-up7", 209, -6),
  cue("Swish: 225", "ad3-swish", 225, -8),
  cue("Pop: item 1", "ad3-pop", 233, -14),
  cue("Pop: item 2", "ad3-pop", 235, -14),
  cue("Pop: item 3", "ad3-pop", 237, -14),
  cue("Tap: 247", "ad3-tap", 247, -6),
  cue("Chime: brightest", "ad3-chime", 258, 0),
  cue("Swish: 270", "ad3-swish", 270, -8),
  cue("Ding: root", "ad3-ding", 275, -4),
  cue("Ding: third", "ad3-ding-up4", 283, -4),
  cue("Ding: fifth", "ad3-ding-up7", 291, -4),
  cue("Swish: 315", "ad3-swish", 315, -8),
  cue("Scribble", "ad3-scribble", 331, -12),
  cue("Pop: 348", "ad3-pop", 348, -4),
  cue("Swish: 360", "ad3-swish", 360, -8),
  ...typing("soft typing", [366, 368, 369, 371, 373], -18),
  cue("Pop: 374", "ad3-pop", 374, -6),
  cue("Swish: 405", "ad3-swish", 405, -8),
  cue("Tap: toggle click", "ad3-tap", 423, -4),
  cue("Tap: toggle clack", "ad3-tap-up1", 426, -4),
  cue("Swoosh: toggle", "ad3-swoosh", 427, -8),
  cue("Swish: 450", "ad3-swish", 450, -8),
  ...[452, 454, 456, 458, 460, 463, 466].map((from, i) =>
    cue(`Tick: slowing ${i + 1}`, "ad3-tick", from, -8),
  ),
  cue("Pop: 466", "ad3-pop", 466, -6),
  // G1 rather than A1: it lands in the G bar.
  cue("Sub: 466", "ad3-sub-down2", 466, -6),

  // The return (495) and the close (513).
  cue("Swish: 495", "ad3-swish", 495, -8),
  ...typing("typing", [500, 502, 504, 505, 507], -16),
  cue("Pop: rise 1", "ad3-pop", 503, -12),
  cue("Pop: rise 2", "ad3-pop-up4", 505, -12),
  cue("Pop: rise 3", "ad3-pop-up7", 507, -12),
  cue("Tap: confirm", "ad3-tap", 513, 0),
  cue("Confirm", "ad3-confirm", 513, -3),
];

export const Ad3Sound: React.FC = () => {
  const { fps } = useVideoConfig();

  return (
    <>
      <Audio
        name="Music bed"
        src={staticFile("audio/ad3-bed.wav")}
        from={0}
        volume={0.85}
        premountFor={fps}
      />
      {CUES.map((c) => (
        <Audio
          key={c.name}
          name={c.name}
          src={staticFile(`audio/${c.file}.wav`)}
          from={c.from}
          volume={dbToGain(c.db)}
          premountFor={fps}
        />
      ))}
    </>
  );
};
