import { Audio } from "@remotion/media";
import type React from "react";
import { staticFile, useVideoConfig } from "remotion";

// Sound effects, each placed on the visual event it accompanies (frames are
// relative to the start of the Promo composition). Generated by
// scripts/generate-audio.mjs.
export const SoundEffects: React.FC = () => {
  const { fps } = useVideoConfig();

  return (
    <>
      <Audio
        name="Typing"
        src={staticFile("audio/typing.wav")}
        from={2}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: globe"
        src={staticFile("audio/whoosh.wav")}
        from={168}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Ding: pin drop"
        src={staticFile("audio/ding.wav")}
        from={265}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: wipe"
        src={staticFile("audio/whoosh.wav")}
        from={294}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Glitch: line 1"
        src={staticFile("audio/glitch.wav")}
        from={311}
        volume={0.35}
        premountFor={fps}
      />
      <Audio
        name="Glitch: line 2"
        src={staticFile("audio/glitch.wav")}
        from={371}
        volume={0.35}
        premountFor={fps}
      />
      <Audio
        name="Glitch: line 3"
        src={staticFile("audio/glitch.wav")}
        from={431}
        volume={0.35}
        premountFor={fps}
      />
      <Audio
        name="Glitch: switch off"
        src={staticFile("audio/glitch.wav")}
        from={475}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Pop: step 1"
        src={staticFile("audio/pop.wav")}
        from={567}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Pop: step 2"
        src={staticFile("audio/pop.wav")}
        from={612}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Pop: step 3"
        src={staticFile("audio/pop.wav")}
        from={657}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Pop: step 4"
        src={staticFile("audio/pop.wav")}
        from={702}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Pop: step 5"
        src={staticFile("audio/pop.wav")}
        from={747}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Ding: launch"
        src={staticFile("audio/ding.wav")}
        from={757}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: to work"
        src={staticFile("audio/whoosh.wav")}
        from={774}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: card 2"
        src={staticFile("audio/whoosh.wav")}
        from={840}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: card 3"
        src={staticFile("audio/whoosh.wav")}
        from={885}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: card 4"
        src={staticFile("audio/whoosh.wav")}
        from={930}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: card 5"
        src={staticFile("audio/whoosh.wav")}
        from={975}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: card 6"
        src={staticFile("audio/whoosh.wav")}
        from={1020}
        volume={0.3}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: to promises"
        src={staticFile("audio/whoosh.wav")}
        from={1072}
        volume={0.4}
        premountFor={fps}
      />
      <Audio
        name="Pop: promise 1"
        src={staticFile("audio/pop.wav")}
        from={1080}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Pop: promise 2"
        src={staticFile("audio/pop.wav")}
        from={1110}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Pop: promise 3"
        src={staticFile("audio/pop.wav")}
        from={1140}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Whoosh: fast"
        src={staticFile("audio/whoosh.wav")}
        from={1166}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Pop: promise 5"
        src={staticFile("audio/pop.wav")}
        from={1200}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Click: CTA"
        src={staticFile("audio/click.wav")}
        from={1348}
        volume={0.7}
        premountFor={fps}
      />
      <Audio
        name="Ding: CTA"
        src={staticFile("audio/ding.wav")}
        from={1351}
        volume={0.35}
        premountFor={fps}
      />
    </>
  );
};
